FROM golang:1.24.5-alpine3.22

WORKDIR /marketplace

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY internal/ ./internal
COPY scripts/ ./scripts

ENV CGO_ENABLED=1