FROM golang:1.24.5-alpine3.22

WORKDIR /marketplace

RUN apk add --no-cache curl

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5

COPY go.mod go.sum ./
COPY cmd/ ./cmd
COPY internal/ ./internal

CMD ["/bin/sh", "-c", "golangci-lint --version && golangci-lint run"]